# Generated by Django 5.0 on 2024-06-10 15:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Адрес филиала')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('rating', models.CharField(max_length=255, verbose_name='Рейтинг филиала')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('url_adress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Как доехать')),
                ('h', models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта')),
                ('d', models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Филиалы',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField()),
                ('phonenumber', models.CharField(max_length=225)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование салона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('rating', models.CharField(max_length=255, verbose_name='Рейтинг салона')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Service_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=255, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Виды услуги',
                'verbose_name_plural': 'Виды услуги',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name=' Фамилия')),
                ('nameofmaster', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('experience', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('reiting', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('direction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Направление')),
                ('procent_summ', models.IntegerField(blank=True, null=True, verbose_name='Процент от записи')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_master', to='pages.branch', verbose_name='Филиал')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_info_mov', to=settings.AUTH_USER_MODEL, verbose_name='Выберите пользователя')),
            ],
            options={
                'verbose_name': 'Данные мастера',
                'verbose_name_plural': 'Данные мастеров',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('A', 'Администратор'), ('M', 'Менеджер')], default='A', max_length=255, verbose_name='Наименование')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_person', to='pages.branch', verbose_name='Филиал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement', to=settings.AUTH_USER_MODEL, verbose_name='Выберите пользователя')),
            ],
            options={
                'verbose_name': 'Движения',
                'verbose_name_plural': 'Движения',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon', to='pages.salons', verbose_name='Салон'),
        ),
        migrations.CreateModel(
            name='Master_and_service_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_and_service_view', to='pages.master', verbose_name='Выберите мастера')),
                ('service_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_and_service_view_1', to='pages.service_view', verbose_name='Выберите услугу')),
            ],
            options={
                'verbose_name': 'Услуги Мастера',
                'verbose_name_plural': 'Услуги Мастера',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('queue_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Очередь')),
                ('rating', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рейтинг услуги')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='pages.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='service_view',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_view', to='pages.services', verbose_name='Выберите услугу'),
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.CharField(blank=True, max_length=225, null=True)),
                ('services', models.CharField(blank=True, max_length=5000, null=True)),
                ('price', models.CharField(blank=True, max_length=225, null=True)),
                ('status', models.CharField(blank=True, max_length=225, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=225, null=True)),
                ('date_rec_info', models.DateField(blank=True, null=True)),
                ('date_rec', models.CharField(blank=True, max_length=225, null=True)),
                ('feedback', models.CharField(blank=True, max_length=225, null=True)),
                ('time_info', models.CharField(blank=True, max_length=225, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('feedback_rev', models.CharField(blank=True, max_length=225, null=True)),
                ('master_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_record', to='pages.master', verbose_name='Выберите мастера')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('services_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_user', to='pages.services')),
            ],
            options={
                'verbose_name': 'Записи',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date_rec_info'],
            },
        ),
    ]
