# Generated by Django 5.0 on 2024-06-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='email_of',
            field=models.EmailField(blank=True, max_length=225, null=True, verbose_name='Дополнительное поле для почты'),
        ),
        migrations.AddField(
            model_name='records',
            name='name_of',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Дополнительное поле для имени'),
        ),
    ]
