# Generated by Django 5.0 on 2024-06-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_records_email_of_records_name_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
