# Generated by Django 5.0 on 2024-06-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_branch_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Электронная почта филиала'),
        ),
    ]
