# Generated by Django 5.0 on 2024-06-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_branch_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Электронная почта филиала'),
        ),
    ]
