# Generated by Django 5.0 on 2024-06-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_branch_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='position',
            field=models.CharField(choices=[('A', 'Администратор'), ('M', 'Менеджер'), ('D', 'Директор')], default='A', max_length=255, verbose_name='Наименование'),
        ),
    ]
