# Generated by Django 5.0 on 2024-06-11 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_movement_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salons_person', to='pages.salons', verbose_name='Салон'),
        ),
    ]
