# Generated by Django 5.0 on 2024-05-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_alter_records_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'ordering': ['-date_rec_info'], 'verbose_name': 'Записи', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='records',
            name='date_rec_info',
            field=models.DateField(blank=True, null=True),
        ),
    ]
