# Generated by Django 5.0 on 2024-05-28 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_records_time_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('A', 'Администратор'), ('M', 'Менеджер')], default='A', max_length=255, verbose_name='Наименование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement', to=settings.AUTH_USER_MODEL, verbose_name='Выберите услугу')),
            ],
            options={
                'verbose_name': 'Виды услуги',
                'verbose_name_plural': 'Виды услуги',
            },
        ),
    ]
