# Generated by Django 5.0 on 2024-05-28 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='master_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_record', to='pages.master', verbose_name='Выберите мастера'),
        ),
    ]
