# Generated by Django 5.0 on 2024-05-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_records_feedback_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='url_adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Как доехать'),
        ),
    ]
