# Generated by Django 5.0 on 2024-05-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_branch_url_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='d',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='branch',
            name='h',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта'),
        ),
    ]
