# Generated by Django 5.0 on 2024-05-29 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_branch_d_branch_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_person', to='pages.branch', verbose_name='Филиал'),
        ),
    ]
