# Generated by Django 5.0 on 2024-05-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_movement_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='procent_summ',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процент от записи'),
        ),
    ]
