# Generated by Django 5.0.3 on 2024-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_master_procent_summ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Данные мастера', 'verbose_name_plural': 'Данные мастеров'},
        ),
        migrations.AddField(
            model_name='master',
            name='last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Фамилия мастера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Адрес филиала'),
        ),
        migrations.AlterField(
            model_name='master',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.CharField(max_length=255, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='master',
            name='nameofmaster',
            field=models.CharField(max_length=255, verbose_name='Имя мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='master',
            name='reiting',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
