# Generated by Django 5.0.3 on 2024-06-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_alter_master_options_master_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salons',
            options={'verbose_name': 'Салон', 'verbose_name_plural': 'Салоны'},
        ),
        migrations.RemoveField(
            model_name='master',
            name='last_name',
        ),
        migrations.AddField(
            model_name='master',
            name='surname',
            field=models.CharField(default=1, max_length=255, verbose_name=' Фамилия мастера'),
            preserve_default=False,
        ),
    ]
